SistemaContable/SistemaContable/urls.py
# from rest_framework import routers
from django.conf.urls import url, include
from django.contrib import admin

# router = routers.DefaultRouter()
# router.register(r'accounts', 'apps.Account.views.AccountViewSet')
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('apps.Account.urls')),
    url(r'^', include('apps.home.urls')),
    # url(r'^api', include(router.urls)),
    # url(r'^api-auth/',
    # include('rest_framework.urls', namespace='rest_framework'))
]

SistemaContable/apps/Account/urls.py
from django.conf.urls import url
from . import views

app_name = 'account'
urlpatterns = [
    url(r'^$', views.getAccountsStructure, name='getAccountsStructure'),
    url(r'^account/$', views.listAccounts, name='listAccounts'),
    url(r'^categories/$', views.listCategories, name='listCategories'),
    url(r'^account/new/$', views.newAccount, name='newAccount'),
    url(r'^account/(?P<pk>[0-9]+)/$', views.rudAccount,
        name='rudAccout'),
    url(r'^subaccount/$', views.listSubAccounts, name='listSubAccounts'),
    url(r'^subaccount/new/$', views.newSubAccount, name='newSubAccount'),
    url(r'^subaccount/(?P<pk>[0-9]+)/$', views.rudSubAccount,
        name='rudSubAccount'),
     ]

SistemaContable/apps/home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.home, name='home'), ]

SistemaContable/apps/Account/models.py
from django.db import models

# Create your models here.


class AccountCategory(models.Model):
    name = models.CharField(max_length=15)

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=150)
    category = models.ForeignKey(AccountCategory, blank=True, null=True)

    def __str__(self):
    	return self.name

class SubAccount(models.Model):
    name = models.CharField(max_length=150)
    account = models.ForeignKey(Account)

    def __str__(self):
    	return self.name

class SubSubAccount(models.Model):
    name = models.CharField(max_length=150)
    subAccount = models.ForeignKey(SubAccount)

    def __str__(self):
    	return self.name

SistemaContable/apps/home/models.py
from django.db import models

# Create your models here.

SistemaContable/apps/Account/views.py
from rest_framework.parsers import JSONParser
from rest_framework import viewsets
from .models import Account, SubAccount, SubSubAccount, AccountCategory
from .serializers import AccountSerializer, SubAccountSerializer, CategorySerializer
from django.http import JsonResponse, HttpResponse
from rest_framework.response import Response
from rest_framework import status
from django.views.decorators.csrf import csrf_exempt
# from rest_framework.renderers import JSONRenderer
# from rest_framework.parsers import JSONParser

# Account Model CRUD


@csrf_exempt
def newAccount(request):
    # This view creates a new Account.
    if request.method == 'POST':
        data = JSONParser().parse(request)
        serializer = AccountSerializer(data=data)
        if serializer.is_valid():
            #get category from request
            try:
                # if user pick a category get the id and get the category instance
                # and pass to serializer and save
                category = AccountCategory.objects.get(pk=int(data['category_id']))
                serializer.save(category=category)
            except:
                # else save account without a category
                serializer.save()
            return JsonResponse(serializer.data, status=status.HTTP_201_CREATED)

        return JsonResponse(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

def listCategories(request):
    "List all categories for accounts"
    categories = AccountCategory.objects.all()
    serializer = CategorySerializer(categories, many=True)
    return JsonResponse(
        serializer.data, safe=False,
    )


@csrf_exempt
def listAccounts(request):
    # This view lists the Account model existing objetcs.
    if request.method == 'GET':
        accounts = Account.objects.all()
        serializer = AccountSerializer(accounts, many=True)
        return JsonResponse(
            serializer.data, safe=False,
            json_dumps_params={'indent': 2})


@csrf_exempt
def rudAccount(request, pk):
    # This view reads, updates or deletes an Account
    try:
        account = Account.objects.get(pk=pk)
    except Account.DoesNotExist:
        return HttpResponse(status=404)
    # Reads
    if request.method == 'GET':
        serializer = AccountSerializer(account, many=False)
        return JsonResponse(
            serializer.data, safe=False,
            json_dumps_params={'indent': 2}
        )
    # Updates
    elif request.method == 'PUT':
        data = JSONParser().parse(request)
        serializer = AccountSerializer(account, data=data)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data)
        return JsonResponse(serializer.errors, status=400)

    # Deletes
    elif request.method == 'DELETE':
        account.delete()
        return HttpResponse(status=204)


# Sub Account model CRUD


def newSubAccount(request):
    # This view creates a new SubAccount
    if request.method == 'POST':
        serializer = SubAccountSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data, status=status.HTTP_201_CREATED)
        return JsonResponse(serializer.data, status=status.HTTP_400_BAD_REQUEST)    


@csrf_exempt
def listSubAccounts(request):
    # This view lists the Account model existing objetcs.
    if request.method == 'GET':
        subAccounts = SubAccount.objects.all()
        serializer = SubAccountSerializer(subAccounts, many=True)
        return JsonResponse(
            serializer.data, safe=False,
            json_dumps_params={'indent': 2})


def rudSubAccount(request, pk):
    # This view reads, updates or deletes a SubAccount
    try:
        subaccount = SubAccount.objects.get(pk=pk)
    except SubAccount.DoesNotExist:
        return HttpResponse(status=404)

    # Reads
    if request.method == 'GET':
        serializer = SubAccountSerializer(subaccount, many=False)
        return JsonResponse(
            serializer.data, safe=False,
            json_dumps_params={'indent': 2})
    # Updates
    if request.method == 'PUT':
        data = JSONParser().parse(request)
        serializer = AccountSerializer(Account, data=data)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(
                serializer.data, safe=False,
                json_dumps_params={'indent': 2}
                )
    # Deletes
    if request.method == 'DELETE':
        account.delete()
        return HttpResponse(staus=204)


def getAccountsStructure(request):
    """ This view gets the whole structure of the account app and returns json.
    It loops through each account, subaccount, subsubaccount to create the json
    file
    """
    account_structure = []
    subaccountsList = []
    subsubaccountsList = []
    if request.method == 'GET':
        accounts = Account.objects.all()
        for account in accounts:
            accountData = {
                "AccountID": account.id, "AccountName": account.name,
                # don't get category to avoid NoneType exception
                #"Category": account.category.name
                }
            subaccounts = SubAccount.objects.filter(account=account)
            for subaccount in subaccounts:
                subaccountData = {
                    "SubAccountID": subaccount.id,
                    "SubAccountName": subaccount.name
                }
                subsubaccounts = SubSubAccount.objects.filter(
                    subAccount=subaccount)
                for subsubaccount in subsubaccounts:
                    subsubaccountData = {
                        "SubSubAccountID": subsubaccount.id,
                        "SubSubAccountName": subsubaccount.name}
                    subsubaccountsList.append(subsubaccountData)
                    subaccountData["SubSubAccounts"] = subsubaccountsList
                subaccountsList.append(subaccountData)
                accountData["SubAccounts"] = subaccountsList
            account_structure.append(accountData)
        return JsonResponse(
            account_structure, safe=False, json_dumps_params={'indent': 2})


class AccountViewSet(viewsets.ModelViewSet):
    queryset = Account.objects.all()
    serializer_class = AccountSerializer

SistemaContable/apps/home/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home/home.html')

SistemaContable/apps/home/templates/home/home.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="msapplication-tap-highlight" content="no">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"> {% load staticfiles %}
    <link href="{% static 'css/materialize.css' %}" type="text/css" rel="stylesheet">
    <link href="{% static 'css/materialicons.css' %}" type="text/css" rel="stylesheet">
    <link href="{% static 'css/styles.css' %}" type="text/css" rel="stylesheet">

    <script src="{% static 'js/axios.js' %}"></script>
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/materialize.min.js' %}"></script>
    <script src="{% static 'js/vue.js' %}"></script>
    
</head>

<body>
    <header>
        <nav class="top-nav blue">
            <a href="#" data-activates="nav-mobile" class="button-collapse top-nav full hide-on-large-only"><i class="material-icons">menu</i></a>
            <div class="container">
                <div class="nav-wrapper"><a class="page-title">Contable Demo</a></div>
            </div>
        </nav>

        <ul id="nav-mobile" class="side-nav fixed" style="transform: translateX(-100%);">
            <div class="container">
                <h4>
                    Sistema Contable
                </h4>
                <ul class="collection">
                    <li class="collection-item">Python 3</li>
                    <li class="collection-item">Django</li>
                    <li class="collection-item">Mysql</li>
                    <li class="collection-item">VueJS</li>
                    <li class="collection-item">MaterializeCSS</li>
                </ul>
            </div>
            <hr>

            <ul class="collapsible collapsible-accordion">
                <li>
                    <a class="collapsible-header">Catálogo de Cuentas<i class="material-icons">arrow_drop_down</i></a>
                    <div class="collapsible-body">
                        <ul>
                            <li><a href="#modal1">Agregar Cuenta</a></li>
                        </ul>
                    </div>
                </li>
            </ul>

        </ul>
    </header>
    <main>
        <div class="container">
            <div id="app">
                <ul class="collapsible" data-collapsible="accordion" v-for="account in accounts">
                    <li>
                        <div class="collapsible-header">
                            <% account.AccountID %>
                            <% account.AccountName %>
                        </div>
                        <div class="collapsible-body">
                            <ul v-for="subaccount in account.SubAccounts">
                                <li class="collection-item">
                                    <% account.AccountID %>.
                                    <% subaccount.SubAccountID %>
                                    <% subaccount.SubAccountName %>
                                    <ul v-for="sub_subaccount in subaccount.SubSubAccounts">
                                        <li class="collection-item">
                                            <% account.AccountID %>.
                                            <% subaccount.SubAccountID %>.
                                            <% sub_subaccount.SubSubAccountID %>
                                            <% sub_subaccount.SubSubAccountName %>
                                        </li>
                                    </ul>
                                </li>
                            </ul>                   
                        </div>
                    </li>
                </ul>
            <!-- Modal Structure -->
            <div id="modal1" class="modal">
                <div class="modal-content">
                    <div class="input-field">
                        <h4>Agregar Cuenta</h4>
                        <p>
                            <form id="form_account" v-on:submit.prevent="addAccount" action="{% url 'account:newAccount' %}">
                                <div class="input-field">
                                    <input v-model="newAccount.AccountName" type="text" class="validate">
                                    <label class="active" for="account_name">Nombre</label>
                                </div>
                                <div class="input-field">
                                    <select id="account_category">
                                        <option value="">----</option>
                                        <option v-for="category in categories" v-bind:value="category.id"><% category.name %></option>
                                    </select>
                                    <label>Categoría</label>
                                </div>
                                <button class="waves-effect waves-light btn">Guardar</button>
                            </form>
                        </p>
                    </div>
                </div>
                <div class="modal-footer">
                    <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat">Cancelar</a>
                </div>
            </div>

            </div>



        </div>
    </main>
    <script src="{% static 'js/main/main.js' %}"></script>
    <script src="{% static 'js/ajax/home.js' %}"></script>
</body>

<script>
$(document).ready(function(){
    Materialize.updateTextFields();
    $(".button-collapse").sideNav();
    $('.modal').modal();
});
</script>

</html>